export const ScienceQuizData = [
  {
    question: "What is the first step a virus takes to attack a human body?",
    option1: "It creates antibodies.",
    option2: "It attaches to a host cell.",
    option3: "It produces toxins.",
    option4: "It breaks down food",
    ans: 2,
  },
  {
    question: "What does a virus use to replicate inside the body?",
    option1: "Its own energy",
    option2: "Host cell machinery",
    option3: "External bacteria",
    option4: "Blood cells",
    ans: 2,
  },
  {
    question: "How does the body typically respond to a viral infection?",
    option1: "By producing more viruses",
    option2: "By increasing sugar levels",
    option3: "By creating more host cells",
    option4: "By activating the immune system",
    ans: 4,
  },
  {
    question: "Why can viruses cause diseases?",
    option1: "They consume blood cells",
    option2: "They interfere with normal cell functions",
    option3: "They strengthen the immune system",
    option4: "They produce oxygen",
    ans: 2,
  },
  {
    question: "How can the spread of viruses be prevented?",
    option1: "By eating more",
    option2: "By sleeping less",
    option3: "Through vaccination and hygiene practices",
    option4: "By staying in the sun",
    ans: 3,
  },
];
